/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 04-mai-2023 16:23:48 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 
CREATE EXTENSION IF NOT EXISTS postgis;
 

 
/* Addypes to Columns as  ta dropdown list */

/*site de production*/

CREATE TYPE public.code_group_sp as ENUM(
	'gpr',
	'gps ',
	'grpn ',
	'grps '
	'gphenr '
);
ALTER TYPE  public.code_group_sp OWNER TO postgres;

CREATE type public.type_tern as ENUM(
	'double-tern',
	'simple-tern'
);
ALTER type public.type_tern owner to postgres;



CREATE TYPE public.nom_group_sp as ENUM(
	'groupement de production de rades',
	'groupement de production de sousse ',
	'groupement regional de production nord ',
	'groupement regional de production sud ',
	'groupement energie renouvelable '
);
ALTER TYPE  public.nom_group_sp OWNER TO postgres; 





CREATE TYPE public.etat_sp as ENUM(
	'en service',
	'projete',
	'declasse'

);
ALTER TYPE public.etat_sp OWNER TO postgres;


/*poste source htb */ 

CREATE type public.direction as ENUM(
	'dtet ',
	'dten ',
	'dtec ',
	'dtes '

);
ALTER TYPE public.direction OWNER TO postgres;

CREATE type public.base as ENUM(
	'btn   ',
	'bts  ',
	'bne  ',
	'bno  ',
	'bss ',
	'bmk ',
	'bgm ',
	'bgf ',
	'bgn '

);
ALTER TYPE public.base OWNER TO postgres; 



/*sous poste htb */




CREATE type public.niv_tens as ENUM (
	'3-90kv',
	'4-150kv',
	'5-225kv',
	'6-400kv'
);
ALTER TYPE public.niv_tens OWNER TO postgres;


CREATE type public.mob_poste as ENUM (
	'fix',
	'mobile'

);
ALTER TYPE public.mob_poste OWNER TO postgres; 



CREATE type public.type_poste as ENUM (
	'bd (blinde)',
	'cl (classique)',
	'rb (ring bus)',
	'sm (sous-enveloppe metallique)'
);
ALTER TYPE public.type_poste OWNER TO postgres; 





/*sous poste hta*/




CREATE type public.niv_tens_sphta as ENUM (
	'1-10kv',
	'1-15kv',
	'2-33kv'
);
ALTER TYPE public.niv_tens_sphta OWNER TO postgres;








CREATE type public.cont_comm as ENUM (
	'conventionnel',
	'cnn(control commande numerique)'
);
ALTER TYPE public.cont_comm OWNER TO postgres; 




/*ligne htb*/



CREATE type public.niv_tens_lhtb as ENUM (
	'1-10KV',
	'2-33KV',
	'3-90KV',
	'4-150KV',
	'5-225KV',
	'6-400KV'
);
ALTER TYPE public.niv_tens_lhtb OWNER TO postgres;



CREATE type public.comp_compt as ENUM (
	'400kv',
	'225kv',
	'150kv',
	'90kv',
	'33kv',
	'15kv'
);
ALTER TYPE public.comp_compt OWNER TO postgres;


CREATE type public.nb_tron as ENUM (
	'1',
	'2',
	'3',
	'4',
	'5'
);
ALTER TYPE public.nb_tron OWNER TO postgres;


CREATE type public.tron_balis as ENUM (
	'oui',
	'non'
);
ALTER TYPE public.tron_balis OWNER TO postgres;



CREATE type public.typ_balis as ENUM (
	'sans',
	'diurne_sphere',
	'nocturne_lumineux',
	'autres'
);
ALTER TYPE public.typ_balis OWNER TO postgres;


CREATE type public.cab_gard as ENUM (
	'sans',
	'1 cables',
	'2 cables'
);
ALTER TYPE public.typ_balis OWNER TO postgres;


CREATE type public.nat_gard1 as ENUM (
	'acier',
	'opgw rainure',
	'opgw brins creux',
	'opgw tubulaire',
	'autres'
);
ALTER TYPE public.nat_gard1 OWNER TO postgres;

CREATE type public.nat_gard2 as ENUM (
	'acier',
	'opgw rainure',
	'opgw brins creux',
	'opgw tubulaire',
	'autres'
);
ALTER TYPE public.nat_gard2 OWNER TO postgres;


/* cable hbt sous terrain */







CREATE type public.niv_tens_htb_st as ENUM (
	'1-10kv',
	'2-33kv',
	'3-90kv',
	'4-150kv',
	'5-225kv',
	'6-400kv'
);
ALTER TYPE public.niv_tens_htb_st OWNER TO postgres;



CREATE type public.mode_pose as ENUM (
	'pleine terre',
	'buse enrobee en beton'
);
ALTER TYPE public.mode_pose OWNER TO postgres;



CREATE type public.disp_phase as ENUM (
	'en trefle',
	'en nappe',
	'autres'
);
ALTER TYPE public.disp_phase OWNER TO postgres;


CREATE type public.sect_cond as ENUM (
	'400kv',
	'225kv',
	'150kv',
	'90kv',
	'33kv',
	'10kv'
);
ALTER TYPE public.sect_cond OWNER TO postgres;



CREATE type public.gaine as ENUM (
	'plombe',
	'alu soude',
	'alu contre-colle',
	'corrugue',
	'autres'
);
ALTER TYPE public.gaine OWNER TO postgres;

/*jonction htb*/





CREATE type public.type_jonc as ENUM(
	'rubanee',
	'premoulee',
	'autres'

);
ALTER TYPE public.type_jonc OWNER TO postgres;



CREATE type public.motif_jonc as ENUM(
	'initial ',
	'reparation ',
	'changet trace',
	'autres'

);
ALTER TYPE public.motif_jonc OWNER TO postgres;


/*support htb*/










CREATE type public.fam_pylone as ENUM (
	'abc_chat',
	'jmr_double_drapeau',
	'nts_triangle',
	'dfg_double_drapeau',
	'da_db_dc_dd_double_drapeau',
	'sc_sd_4.5_triangle',
	'a2_b2_c2_double_drapeau_400_kv',
	'lpqv_triangle_400kv'
);
ALTER TYPE public.fam_pylone OWNER TO postgres;



CREATE type public.disp_pyl as ENUM (
	'al',
	'anti_cascade',
	'angle',
	'arret'
);
ALTER TYPE public.disp_pyl OWNER TO postgres;


CREATE type public.typ_armemt as ENUM (
	'simple suspension',
	'double suspension',
	'suspension en ve inverse',
	'suspension en ve',
	'pilot simple',
	'simple tension',
	'eclateur à simple tension',
	'double tension'

);
ALTER TYPE public.typ_armemt OWNER TO postgres;



CREATE type public.typ_balisa as ENUM (
	'sans',
	'diurne_peinture',
	'nocturne_lumineux',
	'autres'

);
ALTER TYPE public.typ_balisa OWNER TO postgres;


CREATE type public.typ_isol as ENUM (
	'aero-dynamique',
	'anti-pollution',
	'120kn (simple standard)',
	'autres'

);
ALTER TYPE public.typ_isol OWNER TO postgres;



CREATE type public.mat_isol as ENUM (
	'composite',
	'verre',
	'porcelaine',
	'autres'

);
ALTER TYPE public.mat_isol OWNER TO postgres;


 

 

 

/* Drop Tables */

DROP TABLE IF EXISTS cable_htb_souterrain CASCADE
;

DROP TABLE IF EXISTS jonction_htb CASCADE
;

DROP TABLE IF EXISTS ligne_htb CASCADE
;

DROP TABLE IF EXISTS site_du_production CASCADE
;

DROP TABLE IF EXISTS source_htb CASCADE
;

DROP TABLE IF EXISTS sous_poste_hta CASCADE
;

DROP TABLE IF EXISTS sous_poste_htb CASCADE
;

DROP TABLE IF EXISTS support_htb CASCADE
;

/* Create Tables */

CREATE TABLE cable_htb_souterrain
(
	id serial NOT NULL,
	code_htb_st varchar(10) NULL,
	code_ps varchar(10) NULL,
	code_group public.code_group_sp,
	code_metier varchar(14)NULL,
	direction public.direction ,
	base public.base NULL,
	ur varchar(5) NULL,
	uf varchar(7) NULL,
	ut varchar(10) NULL,
	comp_compt public.comp_compt ,
	bdm_cable varchar(50) NULL,
	nom_cable varchar(50) NULL,
	niv_tens public.niv_tens_htb_st,
	l_ligne_km real NULL,
	pui_app real NULL,
	i_adm_a real NULL,
	i_cc real NULL,
	rl real NULL,
	mode_pose public.mode_pose ,
	disp_phase public.disp_phase ,
	nat_cond varchar(30) NULL,
	sect_cond public.sect_cond ,
	gaine public.gaine ,
	diam_ext real NULL,
	poids smallint NULL,
	prof_long text NULL,
	ref_plan text NULL,
	car_deroul text NULL,
	fo_deroul text NULL,
	marche_no varchar(30) NULL,
	titul_marc varchar(30) NULL,
	etud_proj varchar(30) NULL,
	s_traintant varchar(30) NULL,
	dms date NULL,
	arrete text NULL,
	maint text NULL,
	geom_cbl_st_htb geometry(linestring, 32632) NULL,
	cree_par varchar(20) NULL,
	cree_le timestamp without time zone NULL,
	maj_par varchar(50) NULL,
	maj_le timestamp without time zone NULL,
	obs text NULL
)
;

CREATE TABLE jonction_htb
(
	id serial NOT NULL,
	code_jonct varchar(12) NULL,
	code_htb_st varchar(10) NULL,
	code_metier varchar(20)NULL,
	direction public.direction ,
	base public.base ,
	bdm_jonc varchar(20) NULL,
	bdm_cable varchar(20) NULL,
	bdm_niche varchar(20) NULL,
	type_jonc public.type_jonc ,
	motif_jonc public.motif_jonc ,
	x_32632 integer NULL,
	y_32632 integer NULL,
	ref_plan text NULL,
	dms date NULL,
	geom_j_htb geometry(point, 32632) NULL,
	cree_par varchar(20) NULL,
	cree_le timestamp without time zone NULL,
	maj_par varchar(20) NULL,
	maj_le timestamp without time zone NULL,
	obs text NULL
)
;

CREATE TABLE ligne_htb
(
	id serial NOT NULL,
	code_lhtb varchar(10) NULL,
	code_ps varchar(10) NULL,
	code_metier varchar(14)NULL,
	direction public.direction,
	base public.base NULL,
	ur varchar(5) NULL,
	uf varchar(7) NULL,
	ut varchar(10) NULL,
	comp_compt public.comp_compt ,
	bdm_ligne varchar(50) NULL,
	niv_tens public.niv_tens_lhtb,
	nom_ligne varchar(50) NULL,
	nb_tron public.nb_tron ,
	bdm_tron varchar(50) NULL,
	type_tern public.type_tern NULL,
	l_ligne_km real NULL,
	l_tron_km real NULL,
	tron_balis public.tron_balis ,
	typ_balis public.typ_balis ,
	nat_cond varchar(30) NULL,
	sect_cond varchar(10) NULL,
	cab_gard public.cab_gard ,
	nat_gard1 public.nat_gard1 ,
	sect_gard1 varchar(10) NULL,
	nat_gard2 public.nat_gard2 ,
	sect_gard2 real NULL,
	i_adm_a real NULL,
	p_app_mva real NULL,
	bdm_surplo varchar(20) NULL,
	prof_long varchar(200) NULL,
	ref_plan varchar(100) NULL,
	marche_no varchar(30) NULL,
	titul_marc varchar(30) NULL,
	etud_proj varchar(30) NULL,
	s_traitant varchar(30) NULL,
	dms date NULL,
	arrete varchar(200) NULL,
	geom_ligne_htb geometry(linestring, 32632) NULL,
	cree_par varchar(20) NULL,
	cree_le timestamp without time zone NULL,
	maj_par varchar(20) NULL,
	maj_le timestamp without time zone NULL,
	obs text NULL
)
;

CREATE TABLE site_du_production
(
	id_prod serial NOT NULL,
	code_group public.code_group_sp  ,
	nom_group public.nom_group_sp ,
	code_metier varchar(6)NULL,
	nom_centr varchar(50) NULL,
	ur varchar(5) NULL,
	uf varchar(7) NULL,
	ut varchar(10) NULL,
	comp_compt public.comp_compt,
	nb_groupes smallint NULL,
	type varchar(10) NULL,
	pui_ins real NULL,
	const varchar(30) NULL,
	localite varchar(30) NULL,
	x_32632 integer NULL,
	y_32632 integer NULL,
	geom_sp geometry(polygon, 32632) NULL,
	surface real NULL,
	etat_sp public.etat_sp NULL,
	dms date NULL,
	cree_par varchar(20) NULL,
	cree_le timestamp without time zone NULL,
	maj_par varchar(20) NULL,
	maj_le timestamp without time zone NULL,
	obs text NULL
)
;

CREATE TABLE source_htb 
(
	id_htb serial NOT NULL,
	code_ps varchar(10) NULL,
	code_group public.code_group_sp NULL,
	code_metier varchar(4)NULL,
	direction public.direction ,
	base public.base  ,
	ur varchar(5) NULL,
	uf varchar(7) NULL,
	ut varchar(10) NULL,
	comp_compt public.comp_compt ,
	localite varchar(30) NULL,
	bdm_poste varchar(4) NULL,
	gto_poste varchar(50) NULL,
	salle_cmde varchar(20) NULL,
	nom_poste varchar(50) NULL,
	puiss_mva varchar(30) NULL,
	niv_tens public.niv_tens ,
	"X_32632" integer NULL,
	"Y_32632" integer NULL,
	geom_htb geometry(polygon, 32632) NULL,
	surface real NULL,
	dms date NULL,
	id_ass varchar(8) NULL,
	maint varchar(200) NULL,
	sch_unif varchar(200) NULL,
	gouv varchar(30) NULL,
	deleg varchar(30) NULL,
	cree_par varchar(20) NULL,
	cree_le timestamp without time zone NULL,
	maj_par varchar(20) NULL,
	maj_le timestamp without time zone NULL,
	obs text NULL
)
;

CREATE TABLE sous_poste_hta
(
	id serial NOT NULL,
	code_group varchar(4) NULL,
	code_ps varchar(10) NULL,
	code_metier varchar(8)NULL,
	direction public.direction  ,
	base public.base NULL,
	bdm_poste varchar(20) NULL,
	nom_poste varchar(50) NULL,
	niv_tens public.niv_tens_sphta,
	cont_comm public.cont_comm NULL,
	type_poste public.type_poste ,
	mob_poste public.mob_poste NULL,
	pui_mva smallint NULL,
	nb_av_tr smallint NULL,
	nb_av_rsv smallint NULL,
	nb_dep smallint NULL,
	nb_cel_rsv smallint NULL,
	nb_cel_tot smallint NULL,
	etat public.etat_sp NULL,
	sch_unifil varchar(30) NULL,
	geom_sp geometry(polygon, 32632) NULL,
	surface real NULL,
	dms date NULL,
	das date NULL,
	cree_par varchar(20) NULL,
	cree_le timestamp without time zone NULL,
	maj_par varchar(20) NULL,
	maj_le timestamp without time zone NULL,
	obs text NULL
)
;

CREATE TABLE sous_poste_htb
(
	id serial NOT NULL,
	code_shtb VARCHAR(8),
	code_group public.code_group_sp NULL,
	code_ps varchar(10) NULL,
	code_metier varchar(8)NULL,
	direction public.direction ,
	base  public.direction ,
	bdm_poste varchar(20) NULL,
	nom_poste varchar(50) NULL,
	mob_poste varchar(6) NULL,
	niv_tens public.niv_tens ,
	type_poste public.type_poste ,
	nb_travees varchar(2) NULL,
	etat public.etat_sp NULL,
	sch_unifil varchar(30) NULL,
	geom_sp_htb geometry(polygon, 32632) NULL,
	surface real NULL,
	dms date NULL,
	das date NULL,
	cree_par varchar(20) NULL,
	cree_le timestamp without time zone NULL,
	maj_par varchar(20) NULL,
	maj_le timestamp without time zone NULL,
	obs text NULL
)
;

CREATE TABLE support_htb
(
	id serial NOT NULL,
	code_sup varchar(12) NULL,
	code_lhtb varchar(10) NULL,
	code_metier varchar(20)NULL,
	direction public.direction ,
	base public.base NULL,
	ur varchar(5) NULL,
	uf varchar(7) NULL,
	ut varchar(10) NULL,
	comp_comt public.comp_compt ,
	no_py_site varchar(10) NULL,
	code_bdm varchar(20) NULL,
	bdm_1etern varchar(20) NULL,
	bdm_2etern varchar(20) NULL,
	localite varchar(30) NULL,
	x_32632 integer NULL,
	y_32632 integer NULL,
	fam_pylone public.fam_pylone ,
	typ_pylone varchar(5) NULL,
	ext_pylone varchar(10) NULL,
	disp_pyl public.disp_pyl ,
	angle_deg real NULL,
	h_totale_m real NULL,
	typ_armemt public.typ_armemt ,
	typ_balisa public.typ_balisa ,
	nuan_acier varchar(30) NULL,
	h_acc_bass real NULL,
	poids_kg real NULL,
	typ_massif varchar(12) NULL,
	l_portee_m real NULL,
	typ_isol public.typ_isol,
	mat_isol public.mat_isol ,
	nb_isol_ch smallint NULL,
	photo text NULL,
	ref_plan varchar(100) NULL,
	marche_no varchar(30) NULL,
	dms date NULL,
	cree_par varchar(20) NULL,
	cree_le timestamp without time zone NULL,
	maj_par varchar(20) NULL,
	maj_le timestamp without time zone NULL,
	obs text NULL,
	geom_supp_htb geometry(point, 32632) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE cable_htb_souterrain ADD CONSTRAINT "PK_cable_HTB_souterrain"
	PRIMARY KEY (id)
;

ALTER TABLE cable_htb_souterrain 
  ADD CONSTRAINT un_jnc UNIQUE (code_htb_st)
;

CREATE INDEX "IXFK_cable_HTB_souterrain_Post_HTB" ON cable_htb_souterrain (id ASC)
;

CREATE INDEX "IXFK_cable_htb_souterrain_source_htb" ON cable_htb_souterrain (code_ps ASC)
;

ALTER TABLE jonction_htb ADD CONSTRAINT "PK_jonction_HTB"
	PRIMARY KEY (id)
;

ALTER TABLE jonction_htb 
  ADD CONSTRAINT un_jonc UNIQUE (code_jonct)
;

CREATE INDEX "IXFK_jonction_HTB_cable_HTB_souterrain" ON jonction_htb (id ASC)
;

CREATE INDEX "IXFK_jonction_htb_cable_htb_souterrain_02" ON jonction_htb (code_htb_st ASC)
;

ALTER TABLE ligne_htb ADD CONSTRAINT "PK_ligne_HTB"
	PRIMARY KEY (id)
;

ALTER TABLE ligne_htb 
  ADD CONSTRAINT un_lhtb UNIQUE (code_lhtb)
;

CREATE INDEX "IXFK_ligne_HTB_Post_HTB" ON ligne_htb (id ASC)
;

CREATE INDEX "IXFK_ligne_htb_source_htb" ON ligne_htb (code_ps ASC)
;


ALTER TABLE site_du_production ADD CONSTRAINT "PK_site_du_production"
	PRIMARY KEY (id_prod)
;

ALTER TABLE site_du_production 
  ADD CONSTRAINT un_sp UNIQUE (code_group)
;

ALTER TABLE source_htb ADD CONSTRAINT "PK_source_HTB "
	PRIMARY KEY (id_htb)
;

ALTER TABLE source_htb 
  ADD CONSTRAINT un_ps UNIQUE (code_ps)
;

CREATE INDEX "IXFK_source_htb_site_du_production" ON source_htb (code_group ASC)
;

ALTER TABLE sous_poste_hta ADD CONSTRAINT "PK_sous_poste_HTA"
	PRIMARY KEY (id)
;

ALTER TABLE sous_poste_hta 
  ADD CONSTRAINT un_hta UNIQUE (code_group)
;

CREATE INDEX "IXFK_sous_poste_HTA_Post_HTB" ON sous_poste_hta (id ASC)
;

CREATE INDEX "IXFK_sous_poste_hta_source_htb" ON sous_poste_hta (code_ps ASC)
;

ALTER TABLE sous_poste_htb ADD CONSTRAINT "PK_sous_poste_HTB"
	PRIMARY KEY (id)
;

ALTER TABLE sous_poste_htb 
  ADD CONSTRAINT un_htb UNIQUE (code_group)
;

CREATE INDEX "IXFK_sous_poste_HTB_Post_HTB" ON sous_poste_htb (id ASC)
;

CREATE INDEX "IXFK_sous_poste_htb_source_htb" ON sous_poste_htb (code_ps ASC)
;

ALTER TABLE support_htb ADD CONSTRAINT "PK_support_HTB"
	PRIMARY KEY (id)
;

ALTER TABLE support_htb 
  ADD CONSTRAINT un_sup UNIQUE (code_sup)
;

CREATE INDEX "IXFK_support_HTB_ligne_HTB" ON support_htb (id ASC)
;

CREATE INDEX "IXFK_support_htb_ligne_htb_02" ON support_htb (code_lhtb ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE cable_htb_souterrain ADD CONSTRAINT "FK_cable_htb_souterrain_source_htb"
	FOREIGN KEY (code_ps) REFERENCES source_htb (code_ps) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE jonction_htb ADD CONSTRAINT "FK_jonction_htb_cable_htb_souterrain"
	FOREIGN KEY (code_htb_st) REFERENCES cable_htb_souterrain (code_htb_st) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ligne_htb ADD CONSTRAINT "FK_ligne_htb_source_htb"
	FOREIGN KEY (code_ps) REFERENCES source_htb (code_ps) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE source_htb ADD CONSTRAINT "FK_source_htb_site_du_production"
	FOREIGN KEY (code_group) REFERENCES site_du_production (code_group) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sous_poste_hta ADD CONSTRAINT "FK_sous_poste_hta_source_htb"
	FOREIGN KEY (code_ps) REFERENCES source_htb (code_ps) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sous_poste_htb ADD CONSTRAINT "FK_sous_poste_htb_source_htb"
	FOREIGN KEY (code_ps) REFERENCES source_htb (code_ps) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE support_htb ADD CONSTRAINT "FK_support_htb_ligne_htb"
	FOREIGN KEY (code_lhtb) REFERENCES ligne_htb (code_lhtb) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

 

 

 

 

 

 

 

 
